modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/KleeSlabs/issues"

[[mods]]
modId="kleeslabs"
version="${file.jarVersion}"
displayName="KleeSlabs"
displayURL="https://blay09.net/mods/kleeslabs"
logoFile="kleeslabs-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Break only the half of a double slab that you're looking at.
'''

[[dependencies.kleeslabs]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="balm"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"
